### ISSUE TITLE
can't installl torch-scatter==2.0.7

### ISSUE THREAD

**Issue by GUOGUO-lab** [xuhongzuo/deep-iforest#1]
I can't install torch-scatter==2.0.7 because it tells me that only 2.0.4 and 2.0.5 are supported for torch==1.5.0+cu101, I wonder how can I fix this problem?

'''
pip install --verbose --no-index torch-scatter==2.0.7 -f https://pytorch-geometric.com/whl/torch-1.5.0+cu101.html
ERROR: Could not find a version that satisfies the requirement torch-scatter==2.0.7 (from versions: 2.0.4, 2.0.5)
ERROR: No matching distribution found for torch-scatter==2.0.7
'''

also the same problem for torch-sparse

'''
ERROR: Could not find a version that satisfies the requirement torch-sparse==0.6.9 (from versions: 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7)
ERROR: No matching distribution found for torch-sparse==0.6.9
'''

**Comment by GUOGUO-lab** [comment]
I also tried some other methods, but I think it's the problem of the torch's version

**Comment by xuhongzuo** [comment]
Thanks so much for raising this problem.   
`requirements.txt` has been updated.  
issue closed
