### ISSUE TITLE
meet again

### ISSUE THREAD

**Issue by 943fansi** [xuhongzuo/deep-iforest#2]
@xuhongzuo. Hello!
      I came here when I searched for Isolation Forest Algorithms. Do you have any list of homepages where you showcase your academic work? Just in case I missed any awesome work.

**Comment by xuhongzuo** [comment]
Thank you for your interest. 
Sorry, I have not constructed my homepage. I saw you have repositories with Chinese readme. You can add my Wechat `leoxhz_`  .
