### ISSUE TITLE
Feeding video frame features to the model

### ISSUE THREAD

**Issue by KaidNassima** [xuhongzuo/deep-iforest#3]
hello , firstable i wanna thank you for ur amazing work 
so i have feature vectors extracted from videos and i wanna use ur algorithm to detect anomalies 
my question is , should i modify smthing , cause normally the model takes in tabular , graph or ts form of data

**Comment by xuhongzuo** [comment]
Thanks for your interest, and I'm so sorry for the late reply.

If you already have extracted features from videos, you can save them as CSV files (each line denote a video frame, and each column is a feature), or you can use `DataFrame` of `pandas` to organize them. The data can be seen as tabular data now. Then, you can directly perform deep isolation forest.
