### ISSUE TITLE
Multivariate ts dataset

### ISSUE THREAD

**Issue by jinmang2** [xuhongzuo/deep-iforest#4]
Thanks for your work.
The UCR natural dataset in your repository is a univariate dataset. Does DIF also support multi-variate time series dataset?

**Comment by xuhongzuo** [comment]
Yes, of course. DIF can handle multi-variate time series dataset.

**Comment by jinmang2** [comment]
@xuhongzuo Thank you for answer.
As an additional question, I checked the source code that the argument to perform CERE is `new_ensemble_method`. However, in `main_ts.py`, CERE is not used for time series.
Doesn't ts support CERE?

https://github.com/xuhongzuo/deep-iforest/blob/8eba6acee079069b545fb5a7cb0fe2a07a4403a4/main_ts.py#L39-L49

**Comment by xuhongzuo** [comment]
I am so sorry for the late reply. 
We use a convolutional net for time series data. However, CERE is designed for matrix multiplication, so ts does not support CERE.

**Comment by jinmang2** [comment]
Thanks!
